// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ScrabbleWordScorer
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("word")]
        public string Word { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("total_score")]
        public long TotalScore { get; set; }

        [JsonProperty("letter_count")]
        public long LetterCount { get; set; }

        [JsonProperty("letter_scores")]
        public HighestScoringLetter[] LetterScores { get; set; }

        [JsonProperty("highest_scoring_letter")]
        public HighestScoringLetter HighestScoringLetter { get; set; }

        [JsonProperty("average_letter_score")]
        public double AverageLetterScore { get; set; }

        [JsonProperty("note")]
        public string Note { get; set; }
    }

    public partial class HighestScoringLetter
    {
        [JsonProperty("letter")]
        public string Letter { get; set; }

        [JsonProperty("score")]
        public long Score { get; set; }
    }
}
